name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Execute build commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSHKEY }}
          script: |
            cd GPS
            git reset --hard
            git pull
            npm i
            npm run build

  deploy_frontend:
    runs-on: ubuntu-latest
    needs: build_frontend
    steps:
      - name: Copy files to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.SSHKEY }}
          script: |
            cd GPS
            sudo rsync -av --delete ./build/ /opt/traccar/web/
